config/routes.rb
Registrar::Application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  get "/directory", to: 'directory#index', as: 'directory'
  get '/directory/:id', to: 'directory#show'
  get "/events/:id", to: 'events#show', as: 'events'

  
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  post '/user_courses/update_average', to: 'user_courses#update_average', as: 'update_average'
  get '/user_courses/update_progress', to: 'user_courses#update_progress', as: 'update_progress'
  post '/user_courses/update_time_spent', to: 'user_courses#update_time_spent', as: 'update_time_spent'

  get '/intro' => 'courses#intro'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post '/user_courses/update_progress', to: 'user_courses#update_progress', as: 'update_progress'
  get '/prework', to: 'prework#index', as: 'prework'
  get 'profile', to: 'users#edit', as: 'edit_current_user'

  get '/complete_signup', to: 'users#complete_signup', as: 'complete_signup' 
  post '/complete_signup', to: 'users#complete_signup_update'

  resources :sessions
  resources :users
  resources :courses
  resources :emails

  match '/users/:id/update_codeschool' => 'users#update_codeschool'
  match '/users/:id/update_treehouse' => 'users#update_treehouse'
  match '/users/:id/prework' => 'prework#index', as: 'user_prework'
  match '/signup/:token' => 'users#new'

  get 'progress', to: 'progress#index', as: 'progress'

  root :to => 'application#index'

end

app/views/policer/get_started.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  </head>
  <body>
    <table>
      <tr>
        <td colspan="3">
          <h1>THE FLATIRON SCHOOL</h1>
        </td>
      </tr>
     
      <tr>
        <td colspan="3">
          <p>Hi, <%= @user.first_name.capitalize %></p>
        </td>
      </tr>

      <tr>
        <td colspan="3">
          <p>Thanks for signing up with Ironboard! There's a lot of great material to cover, so get started right away! Listed below are courses due for week one. Each week we'll send you a new list to crush. Happy coding!</p>
        </td>
      </tr>

      <tr>
        <td><p><strong>COURSE</strong></p></td>
        <td><p><strong>EST. TIME</strong></p></td>
        <td><p><strong>PROGRESS %</strong></p></td>
      </tr>

      <% @user.week_one_courses.each do |user_course| %>
      <tr>
        <td><%= link_to user_course.course.name, user_course.course.url%></td>
        <td><%= user_course.course.estimated_time%></td>
        <td><%= user_course.progress%></td>
      </tr>
      <% end %>

      <tr>
        <td colspan="3"><p>Thanks,<br> Avi</p></td>
      </tr>
    </table>
  </body>
</html>

app/views/policer/past_due.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  </head>
  <body>
    <table>
      <tr>
        <td colspan="3">
          <h1>THE FLATIRON SCHOOL</h1>
        </td>
      </tr>
     
      <tr>
        <td colspan="3">
          <p>Hi, <%= @user.first_name.capitalize %></p>
        </td>
      </tr>
     
      <tr>
        <td colspan="3">
          <p>This prework notification is being sent to you becasue you are behind on the following course work:</p>
        </td>
      </tr>

      <tr>
        <td><p><strong>COURSE</strong></p></td>
        <td><p><strong>EST. TIME</strong></p></td>
        <td><p><strong>PROGRESS %</strong></p></td>
      </tr>

      <% @past_due_user_courses.each do |user_course|%>
      <tr>
        <td><%= link_to user_course.course.name, user_course.course.url%></td>
        <td><%= user_course.course.estimated_time%></td>
        <td><%= user_course.progress %></td>
      </tr>
      <% end %>

      <tr>
        <td colspan="3"><p>Thanks,<br> Avi</p></td>
      </tr>
    </table>
  </body>
</html>

app/views/policer/scolding.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style type="text/css">
    </style>
  </head>
  <body>
    <table>
      <tr>
        <td>
          <h1>THE FLATIRON SCHOOL</h1>
        </td>
      </tr>
     
      <tr>
        <td>
          <p>Hi,</p>
        </td>
      </tr>
     
      <tr>
        <td>
          <p><%= @body %></p>
        </td>
      </tr>

        <td><p>Thanks,<br> Avi</p></td>
      </tr>

    </table>
  </body>
</html>

app/views/policer/weekly.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  </head>
  <body>
    <table>
      <tr>
        <td colspan="3">
          <h1>THE FLATIRON SCHOOL</h1>
        </td>
      </tr>
     
      <tr>
        <td colspan="3">
          <p>Hi, <%= @user.first_name.capitalize %></p>
        </td>
      </tr>

      <tr>
        <td colspan="3">
          <p>Welcome to week two, here are the courses to complete:</p>
        </td>
      </tr>

      <tr>
        <td><p><strong>COURSE</strong></p></td>
        <td><p><strong>EST. TIME</strong></p></td>
        <td><p><strong>PROGRESS %</strong></p></td>
      </tr>

      <% @user.send("#{@selected_weeks_courses}").each do |user_course| %>
      <tr>
        <td><%= link_to user_course.course.name, user_course.course.url%></td>
        <td><%= user_course.course.estimated_time%></td>
        <td><%= user_course.progress%></td>
      </tr>
      <% end %>

      <tr>
        <td colspan="3"><p>Thanks,<br> Avi</p></td>
      </tr>
    </table>
  </body>
</html>

app/views/policer/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style type="text/css">
    </style>
  </head>
  <body>
    <table>
      <tr>
        <td>
          <h1>THE FLATIRON SCHOOL</h1>
        </td>
      </tr>
     
      <tr>
        <td>
          <p>Hi, <%= @invite.first_name.capitalize %></p>
        </td>
      </tr>
     
      <tr>
        <td>
          <p>Welcome to Flatiron! Please use the below link to sign up:</p>
        </td>
      </tr>

      <tr>
        <td>
          <p><%= link_to "Sign up to Iron Board", complete_signup_url(:token => @invite.token) %></p>
        </td>
      <tr>
        <td><p>Thanks,<br> BOB</p></td>
      </tr>

    </table>
  </body>
</html>