config/routes.rb
Registrar::Application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  get "/directory", to: 'directory#index', as: 'directory'
  get '/directory/:id', to: 'directory#show'
  get "/events/:id", to: 'events#show', as: 'events'

  
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  post '/user_courses/update_average', to: 'user_courses#update_average', as: 'update_average'
  get '/user_courses/update_progress', to: 'user_courses#update_progress', as: 'update_progress'
  post '/user_courses/update_time_spent', to: 'user_courses#update_time_spent', as: 'update_time_spent'

  get '/intro' => 'courses#intro'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post '/user_courses/update_progress', to: 'user_courses#update_progress', as: 'update_progress'
  get '/prework', to: 'prework#index', as: 'prework'
  get 'profile', to: 'users#edit', as: 'edit_current_user'

  get '/complete_signup', to: 'users#complete_signup', as: 'complete_signup' 
  post '/complete_signup', to: 'users#complete_signup_update'

  resources :sessions
  resources :users
  resources :courses
  resources :emails

  match '/users/:id/update_codeschool' => 'users#update_codeschool'
  match '/users/:id/update_treehouse' => 'users#update_treehouse'
  match '/users/:id/prework' => 'prework#index', as: 'user_prework'
  match '/signup/:token' => 'users#new'

  get 'progress', to: 'progress#index', as: 'progress'

  root :to => 'application#index'

end

app/controllers/prework_controller.rb
class PreworkController < ApplicationController

  def index
    @user_courses = load_user_courses
    @user = User.find(@user_id)

    # all_progress = @student.user_courses.select(:progress)
    # progress_array = all_progress.map {|a| a.progress}
    # @average = progress_array.inject{ |sum, el| sum + el }.to_f / progress_array.size
    @average = @user.overall_progress.round(0)
  
  end

  private

# Load user courses, allow if user_id is current user or admin logged in
  def load_user_courses
    user_id = params[:id].blank? ? authorized_user.id : params[:id].to_i
    if user_id == authorized_user.id || current_admin_user
      user_courses = Course.courses_for_user(user_id)
    else
      redirect_to root_url, notice: "Don't try to be someone you're not."    
    end
    @user_id = user_id
    user_courses
  end

end

app/helpers/prework_helper.rb
module PreworkHelper
end

app/views/prework/_prework_modal.html.erb
<!-- Modal to the Prework Intro -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="font-size:30px;">×</button>
   <center><h2 style="font-size:30px;">Overview</h2></center>
  </div>
  <div class="modal-body">
    <div class="well">
    <section id="overview">
      <%= image_tag "avi.png", :align => "right", :width => "300px" %>

      <p><img src="http://dailydropcap.com/images/I-11-cap.png" title="Daily Drop Cap by Jessica Hische" align="left" alt="I"/>n this document you're going to find a ton of reading, videos, and quizzes that Flatiron students complete before their semester even begins. We thought we'd open source this material. We suggest going through this material linearly because it really represents a progressive journey through the fundamentals and abstractions required to build web applications. Enjoy.</p>

      <p>The main topics we want students to know about before the semester starts are on the left: Internet Basics, Command-Line Interface, Git Version Control, SQL and Databases, HTML, CSS, Javascript and jQuery, Ruby, and Ruby on Rails.</p>

      <p>Each resource has an estimated amount of time it should take you if you have 0 prior knowledge on the topic. In total, if you are coming to this with absolutely no experience, as in, you'd have trouble articulating what the topic even is, then we estimate this work will take you between 80 - 100 hours to complete. If you are a rockstar, this shouldn't take more than 20 hours.</p>

      <p>If you are familiar with the topic, we highly suggest trying to take the quiz or challenge first. If you pass easily and collect the badge, great, move on. That being said, even we found ourselves learning new things during this assessment, so maybe try to watch the videos on the topics with which you are most unfamiliar.</p>

      <p>In terms of reading and watching videos, feel free to skip through - go for overall coverage as opposed to depth - try to read and watch as much as possible and then try to take the quiz. Be quick, and then do a 2nd round of reading and watching.</p>

      <h2 id="setup">Setup</h2>
      <p>
        To complete these units, you will need a <a href="http://teamtreehouse.com" target="_blank">Treehouse</a> and <a href="http://www.codeschool.com/enrollments/dnFtaXFMbXROSVVqT3N1bngwWnBRUjhGc2k1Z1dEOW52cFJvZEMzRUZvRT0tLWpvUElMODBvdFhiZlA4MjE2Mlc2c1E9PQ==">CodeSchool</a> account. They are both normally $25 a month, so figure you might spend $50-$100 depending on how quickly you get through the material. So far the fine folks at <a href="http://www.codeschool.com/enrollments/dnFtaXFMbXROSVVqT3N1bngwWnBRUjhGc2k1Z1dEOW52cFJvZEMzRUZvRT0tLWpvUElMODBvdFhiZlA4MjE2Mlc2c1E9PQ==" target="_blank">CodeSchool</a> have created a $9 trial month for all Flatiron Preworkers. So register using that link. Treehouse will offer something similar soon.
      </p>
      <p>You should also have a Rails Development environment setup. There are lots of guides for that on the internet and depending on your OS and setup, it's a bit of a process. You could always use the cross-platform <a href="http://railsinstaller.org/" target="_blank">Rails Installer</a>.</p>

      <h2 id="thoughts">Thoughts</h2>
      <p>
        One of the challenges in learning how to code is that you probably don't even know what you're suppose to learn. When creating this prework, we had 4 goals in mind.
      </p>
      <ol>
        <li>
          <strong>Full Stack</strong><br />
          To present the full stack of technologies required to build a webapp from the ground up. We don't care if you use ERB or HAML, the web is built on HTML, everyone should learn it. Whether NoSQL or RDBMS, understanding the fundamentals of schema design and SQL is crucial. Students shouldn't shy away from depth. How can you be a web developer without a proficiency in these skills?
        </li>

        <li>
          <strong>Linear Progression</strong><br/ >
          The material is presented in order, going from computer / web basics, to data theory, to markup, to styling, to programming, and then to version control. At that point, you've become familiar enough with general syntax and your computer to start learning to program. You learn the basics of code through Ruby and Javascript and then finally move to Rails that builds upon the rest. Thus you start at the lowest level, the literal HTML the browser renders, and progress up through levels of abstraction until you finally get to the kitchen sink that is the Rails framework. As a beginner, don't try to learn Rails without knowing basic HTML/CSS, Ruby, and Javascript. It's a disservice to your education.
        </li>


        <li>
          <strong>Curated Resources</strong><br/>
          There is such a plethora of amazing content on learning to code. We liked the consistency of going to a few sources that all shared common interfaces and learning patterns, like videos and interactive portions. So this isn't a complete list of all the resources, but more a curated list of what we think works well together (with lots of feedback from alumni). We would love it if you submitted a github issue with more materials you've enjoyed.
        </li>

        <li>
          <strong>Language Agnosticism</strong><br/>
          In the end, programming is about abstractions and expressions, the mechanics of code are universal and exist in all modern languages, python, ruby, and javascript. We teach Ruby because we love it. Thinking your language choice, especially as a beginner, matters, is like thinking that you can only write poetry in English and not in Spanish. Obviously the beauty of poetry is in rhyme and meter, in metaphor and simile, in cadence and rhythm, not in the king's English. Why should code be any different? At Flatiron, you're learning how to think, how to break problems down, how to express yourself, how to abstract ideas, and how to work together. We just learn that through Ruby.
        </li>
      </ol>
      <h2>Why Share It?</h2>
      <p>
        You might be wondering why we would share our curriculum if we are in the education business. First, we honestly do not think that going through this content alone will make anyone a web developer. That's like saying that knowing how to hammer a nail means you can build a house. Sure, you've got the gestures and mechanics down, maybe, but you don't know the first thing about building. There is just so much more to being a developer than the syntax of how to define a method or iterate over an array. We don't focus on content at the Flatiron School. We focus on learning to love code.</p>

        <blockquote>
          <p>If you want to build a ship, don’t drum up the men to gather wood, divide the work and give orders. Instead, teach them to yearn for the vast and endless sea.</p><br>
          <cite><em>Antoine de Saint-Exupery</em></cite>
        </blockquote>
      </p>
    </section>
    </div> <!-- well -->
  </div>
  <div class="modal-footer">
  	<a href="#" class="classname" data-dismiss="modal" aria-hidden="true">close</a>
  </div>
</div>

app/views/prework/_progress_summary.html.erb
    <h4>Overall Progress: <span id="text_overallprogress"><%= @average %>%</span> </h4>
    <h6 id="refresh"><%= link_to "Update Progress", update_progress_path  %></h6>    
    <div class="progress progress-info progress-striped active">
      <div class="bar" id="overallprogress" style="width: <%= @average %>%" >
      </div>
    </div>
<div id="highlight-sidebar">  
      <ul class="nav nav-list">
  
  <% last_subject = nil %>
  <% @user_courses.each do |subject, courses| %>
    <li><%= link_to subject, '#' + subject.downcase.gsub(/\s+/, '').gsub('&', "").gsub(':', "") %></li>
  <% end %>
</div>
  </ul>

app/views/prework/_user_courses.html.erb
<div class="accordion" id="accordion2">
  <% @user_courses.each do |subject, courses| %>
  
  <ul style="list-style: none;">  
    <li><h2 id="<%= subject.downcase.gsub(/\s+/, "").gsub('&', "").gsub(':', "") %>"><%= subject %></h2>

    <div class="subjectdescription">
      <%= courses.first.subject.description %>
    </div>

  </li>
  <% courses.each do |course| %>  
    <li>
      <div class="row">
        <div class="span7">

          <div class="accordion-group">
            <div class="accordion-heading">
      
          <!-- if the course is not treehouse or codeschool show checkbox -->
          <% if course.course_provider_id != 1 && course.course_provider_id != 2 %>
            <% check_value = true if course.user_courses.first.progress > 0 %>
              <%= check_box_tag course.user_courses.first.id, 'yes', check_value, :class => 'regular-checkbox', :style => "margin: 3px;" %>
          <% else %>
            <!-- do nothing -->
          <% end %>

          <!-- when the checkbox is marked the progress bar goes to 100% -->
          <% if course.course_provider_id == 2 %>
            <%= image_tag 'treehouse.png', :width => '25px', :style => "padding: 3px;" %> 
          <% elsif course.course_provider_id == 1 %>
            <%= image_tag 'codeschool.png', :width => '25px', :style => "padding: 3px;" %> 
          <% else %> 
          <% end %><%= link_to course.name, course.url, {:target=> "_blank"} %> :  
            <div style="float: right;">
              <a class="accordion-toggle" style="display: inline; text-decoration: none; color: #0099cc;" data-toggle="collapse" data-parent="#accordion2" href="#collapse<%= course.name.downcase.gsub(/\s+/, "").gsub('&', "").gsub(/'/, "").gsub(/:/, "") %>"><i class="icon-chevron-right" style="margin-top: 7px;"></i></a>
            </div>
            </div>
          </div>

          <div id="collapse<%= course.name.downcase.gsub(/\s+/, "").gsub('&', "").gsub(/'/, "") %>" class="accordion-body collapse out">
            <div class="accordion-inner">
              <span class="descriptionurl">
                <%= course.url %>
              </span>
              <div class="description">
                <%= course.description %>
              </div>
            </div>
          </div>
     

      <div class="row">
        <div class="span3" style="float:left">

        <!-- This is where the timer would be. Button is non-functional at the moment -->

          <%= div_for(course) do %>
            <input type="text" name="timer" id="count<%=course.user_courses.first.id%>" value="<%=course.user_courses.first.time_elapsed%>"/>

            <input type="text" name="timerHMS" id="count-<%=course.user_courses.first.id%>" value="<%=course.user_courses.first.secondstohms%>"/>
            <input type="submit" name="start" value="start" id="count_<%=course.user_courses.first.id%>"/>
            <input type="submit" name="stop" value="stop" id="count_<%=course.user_courses.first.id%>"/>
          <% end %>
        </div>
        <div class="span3" style="float:right;text-align:right" >
          <span class="hours">Estimated time to complete: <%= course.estimated_time %> <a id="tooltip" data-toggle="tooltip" data-placement="right" title="estimation only">Hours</a></span>
          </div>
        </div>
      </div><!-- ends second row with estimated hours -->
    </div>

      <div class="row">
        <div class="span7">
        <% if course.user_courses.first.progress < 100 %>
          <div class="progress progress-warning progress-striped active">
        <% else %>
          <div class="progress progress-warning">
        <% end %>
              <div class="bar" id="bar<%= course.user_courses.first.id %>" style="width: <%= course.user_courses.first.progress %>%" >
              </div>
          </div>
        </div>
      </div>

    </li>     

  <% end %>
  </ul>         
<% end %> 

</div>         
<div style="height:100px"></div>     

app/views/prework/index.html.erb
<title>Iron Board</title><br>

<div class="container prework-container">
	<div class="row">
		<div class="span8 fade-in two" align="center" id="flatiron-background">
			
			<div class="preworkoverview" style="margin-top:160px;">
				<h4 id="prework-button"><%= link_to 'Prework Overview', "#myModal", :'data-toggle' => 'modal' %></h4>	
			</div>
			
		</div>
		
		<div class="span4">
			<div class="well affix fade-in one" data-offset-bottom="200">
				<%= render 'progress_summary' %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="span8">
			<div class="well fade-in two">
				<!-- subjects is an array of our subjects -->

				<%= render 'user_courses' %>

			</div> <!-- well -->
		</div> <!-- span8 -->
	</div> <!-- row -->
</div> <!-- container -->


<%= render 'prework_modal' %>

<script type="text/javascript">
	$(function() {
		var n = noty({
			text: '<%= image_tag 'avi.png', :align => 'left', :width => '80px', :style => 'padding: 4px' %><strong>Avi Flombaum:</strong> <br /> Hi, Welcome to the Prework intro site.  If this is your first time be sure to read the Prework Overview',
			type: 'alert',
			layout: 'bottomRight',
			closeWith: ['click'],
		});
	})

</script>


<!-- End of Modal -->