config/routes.rb
Registrar::Application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  get "/directory", to: 'directory#index', as: 'directory'
  get '/directory/:id', to: 'directory#show'
  get "/events/:id", to: 'events#show', as: 'events'

  
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  post '/user_courses/update_average', to: 'user_courses#update_average', as: 'update_average'
  get '/user_courses/update_progress', to: 'user_courses#update_progress', as: 'update_progress'
  post '/user_courses/update_time_spent', to: 'user_courses#update_time_spent', as: 'update_time_spent'

  get '/intro' => 'courses#intro'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post '/user_courses/update_progress', to: 'user_courses#update_progress', as: 'update_progress'
  get '/prework', to: 'prework#index', as: 'prework'
  get 'profile', to: 'users#edit', as: 'edit_current_user'

  get '/complete_signup', to: 'users#complete_signup', as: 'complete_signup' 
  post '/complete_signup', to: 'users#complete_signup_update'

  resources :sessions
  resources :users
  resources :courses
  resources :emails

  match '/users/:id/update_codeschool' => 'users#update_codeschool'
  match '/users/:id/update_treehouse' => 'users#update_treehouse'
  match '/users/:id/prework' => 'prework#index', as: 'user_prework'
  match '/signup/:token' => 'users#new'

  get 'progress', to: 'progress#index', as: 'progress'

  root :to => 'application#index'

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
	<div class="alert <%= bootstrap_class_for(type) %> fade in">
		<button class="close" data-dismiss="alert" align="right">x</button>
		<%= message %>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- footerwrap -->
<div id="footerwrap">
      <footer class="clearfix"></footer>
	<div class="container">
    <div class="row">
      		<div class="span12">
      			<p><%= link_to "Tim", "http://aspectratio.github.com/" %> - <%= link_to "Dan", "http://firstgeneration.github.io" %> - <%= link_to "Masha", "http://mrikhter.github.io" %> - <%= link_to "Erin", "http://www.erinandcode.com/" %>
      				<br>Crafted With Love - Copyright 2013</p>
      		</div>
		</div><!-- /row -->
	</div><!-- /container -->		
</div><!-- /footerwrap -->

app/views/layouts/_middle.html.erb
<div id="middlewrap">
     <br>
      	<footer class="clearfix"></footer>
      	<div class="container">
      		<div class="row center">
      			<div class="span3">
		      		<div class="dash2-unit">
				        <br>
									<h6>Sign In</h6>
									<p>Sign in as a new user if you don't have an account already.</p>
								<div align='center'><%= image_tag 'device01.png' %></div>
							</div><!-- /dash2-unit -->
      			</div><!-- /span3 -->
				<div class="span3">
		      		<div class="dash2-unit">
				        <br>
				    <h6>Learn</h6>    
						<p style="padding-left:35px;">
							Git
							<br>Ruby on Rails
							<br>Javascript
							<br>SQL & Databases
							<br>HTML5/CSS3
							<br>& more ...
							<h4>See: <%= link_to 'Prework Overview', "#myModal", :'data-toggle' => 'modal' %></h4>	
						</p>
		      		</div><!-- /dash2-unit -->
				</div><!-- /span3 -->
      			<div class="span3">
		      		<div class="dash2-unit">
				        <br>
				        <h6>Progress</h6>
						<p>Keep track of your progress for each course and see your overall progress.</p>
						<div class="progress progress-warning progress-striped active">
				      <div class="bar" id="overallprogress" style="width: 80%;" ></div>
			      </div>
						
					</div><!-- /dash2-unit -->
      			</div><!-- /span3 -->
      			<div class="span3">
		      		<div class="dash2-unit">
				        <br>
				        <h6>Time</h6>
								<p>Keep track of your time with the handy timer for every course.
									<div align="center">
										<%= image_tag 'stat04.png' %>
									</div>
<!-- 									<div>
										<%= image_tag "http://i1283.photobucket.com/albums/a553/erin_lee1/ScreenShot2013-04-14at113851PM_zps734fbdab.png" %>
									</div> -->
								</p>
						
					</div><!-- /dash2-unit -->
      			</div><!-- /span3 -->

      		</div><!-- /row -->
      	</div><!-- /container -->
      </div>


      <%= render 'prework/prework_modal' %>

app/views/layouts/_preworknav.html.erb
<div class="span4">
	<div class="well affix" data-offset-bottom="200">
		<ul class="nav nav-list preworkbar">
			<li><h4>Overall Progress: <span id="text_overallprogress"><%= @average %>%</span> </h4>		
			<div class="progress progress-info progress-striped active">
				<div class="bar" id="overallprogress" style="width: <%= @average %>%" ></div></div></li>
		<% last_subject = nil %>
		<% @user_courses.each do |c| %>
			<% if c.course.subject != last_subject %>
			<% last_subject = c.course.subject %>
			<% if last_subject %>
			<li><strong><%= link_to c.course.subject.name, '#' + c.course.subject.name.downcase.gsub(/\s+/, '') %></strong></li>
			<% end %>
			<% end %>
		<% end %>
		</ul>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Registrar</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

	<!-- NOTY -->
  <%= javascript_include_tag "noty/jquery.noty" %>
  <%= javascript_include_tag "noty/layouts/top" %>
  <%= javascript_include_tag "noty/layouts/topLeft" %>
  <%= javascript_include_tag "noty/layouts/topRight" %>
  <%= javascript_include_tag "noty/layouts/topCenter" %>
  <%= javascript_include_tag "noty/layouts/bottomRight" %>
  <%= javascript_include_tag "noty/themes/default" %>
  <%= javascript_include_tag "ui-noty.js" %>
  <!-- END NOTY -->

  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll" data-target="#highlight-sidebar">
<div class="background"></div><div class="body"></div>
	<div class="lion navbar navbar-inverse">
		<div class="navbar-inner">
			<% if authorized_user %>
			<% @user = authorized_user if !@user %>
			<a href="/" class="brand">Iron Board : <strong><%= @user.first_name %></strong></a>
			<ul class="nav-erin">
	        <li><i class="icon-check icon-white"></i> <%= link_to "Pre-Work", prework_path %></li>
	        <% if !@user.semester_id.blank? %>
	        <li><i class="icon-list-alt icon-white"></i> <%= link_to "Class Directory", directory_path %></li>
	        <li><i class="icon-calendar icon-white"></i> <%= link_to "Calendar", calendar_path %></li>
	        <% end %>
	        <li><i class="icon-user icon-white"></i> <%= link_to "Edit", edit_current_user_path %></li> 
					<li><i class="icon-remove-sign icon-white"></i> <%= link_to "Log Out", logout_path %></li>
				<% else %>
					<%= link_to "Sign Up", signup_path %>
				<% end %>
			</ul>
			
		</div>
	</div>

<%= render partial: "layouts/flash_messages", flash: flash %>
<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/credentials.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Registrar</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="background"></div><div class="body"></div>
  <div class="navbar navbar-inverse">
    <div class="navbar-inner">
      <a class="brand" href="#">Iron Board</a>
    </div>
  </div>
<%= yield %>

<%= render 'layouts/middle' %>
<%= render 'layouts/footer' %>
</body>
</html>